DROP TABLE DEMOCRAT;

DROP SEQUENCE DEMOCRAT_SEQ;

CREATE TABLE DEMOCRAT(
    DEMOCRATNO VARCHAR2(40) NOT NULL, 
    DEMOCRATNOTE CLOB,
    CONSTRAINT PK_DEMOCRAT PRIMARY KEY (DEMOCRATNO)
);

CREATE SEQUENCE DEMOCRAT_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

INSERT INTO DEMOCRAT(DEMOCRATNO) VALUES (DEMOCRAT_SEQ.nextval);

COMMIT;