--------------------------------------------------------
--  Drop Table All
--------------------------------------------------------
DROP TABLE HEALTHLOG;
DROP TABLE NOTIFY;
DROP TABLE Message;
DROP TABLE ChatRoomMember;
DROP TABLE ChatRoom;
DROP TABLE USERPERMISSION;
DROP TABLE PERMISSION;
DROP TABLE BANJIPOST;
DROP TABLE BANJITYPECOURSE;
DROP TABLE REPORT;
DROP TABLE FORUMCOMMENT;
DROP TABLE FORUMPOST;
DROP TABLE FORUMTOPIC;
DROP TABLE COURSEPOST;
DROP TABLE TEACHINGPLAN;
DROP TABLE EVALUATION;
DROP TABLE FINALSCORE;
DROP TABLE REPLY;
DROP TABLE COURSEASK;
DROP TABLE TEACHINGFILE;
DROP TABLE VIDEOLOG;
DROP TABLE VIDEO;
DROP TABLE LEAVE;
DROP TABLE ATTENDANCE;
DROP TABLE TIMETABLE;
DROP TABLE COURSE;
DROP TABLE BASICCOURSE;
DROP TABLE TEACHER;
DROP TABLE STUDENT;
DROP TABLE BANJI;
DROP TABLE BANJITYPE;
DROP TABLE CLASSROOM;
DROP TABLE EMPLOYEE;
DROP TABLE WJLUSER;
--------------------------------------------------------
--  Drop SEQUENCE All
--------------------------------------------------------
DROP SEQUENCE USERPERMISSION_SEQ;
DROP SEQUENCE TEACHER_SEQ;
DROP SEQUENCE EMPLOYEE_SEQ;
DROP SEQUENCE USER_SEQ;
DROP SEQUENCE PERMISSION_SEQ;
DROP SEQUENCE STUDENTNO_SEQ;
DROP SEQUENCE ChatRoomNO_SEQ;
DROP SEQUENCE ChatRoomMemberNO_SEQ;
DROP SEQUENCE MessageNO_SEQ;
DROP SEQUENCE NOTIFY_SEQ;
DROP SEQUENCE BASICCOURSE_SEQ;
DROP SEQUENCE BANJITYPECOURSE_SEQ;
DROP SEQUENCE COURSE_SEQ;
DROP SEQUENCE COURSEPOST_SEQ;
DROP SEQUENCE TEACHINGPLAN_SEQ;
DROP SEQUENCE FINALSCORE_SEQ;
DROP SEQUENCE COURSEASK_SEQ;
DROP SEQUENCE REPLY_SEQ;
DROP SEQUENCE EVALUATION_SEQ;
DROP SEQUENCE CLASSROOM_SEQ;
DROP SEQUENCE TIMETABLE_SEQ;
DROP SEQUENCE VIDEO_SEQ;
DROP SEQUENCE TEACHINGFILE_SEQ;
DROP SEQUENCE VIDEOLOG_SEQ; 
DROP SEQUENCE LEAVE_SEQ;
DROP SEQUENCE ATTENDANCE_SEQ;
DROP SEQUENCE HEALTHLOG_SEQ;
DROP SEQUENCE BANJI_SEQ;
DROP SEQUENCE BANJITYPE_SEQ;
DROP SEQUENCE BANJIPOST_SEQ;
DROP SEQUENCE FORUMTOPIC_SEQ;
DROP SEQUENCE FORUMPOST_SEQ;
DROP SEQUENCE FORUMCOMMENT_SEQ;
DROP SEQUENCE REPORT_SEQ;
--------------------------------------------------------
--  Create Table All
--------------------------------------------------------

CREATE TABLE WJLUSER(
    USERNO VARCHAR2(40) NOT NULL, 
	ACCOUNT VARCHAR2(40 CHAR) NOT NULL, 
	PASSWORD VARCHAR2(40 CHAR) NOT NULL, 
	TYPE NUMBER(8,0) DEFAULT 0 NOT NULL, 
	NAME VARCHAR2(40 CHAR), 
	MAIL VARCHAR2(200), 
	PHONE VARCHAR2(40),
	ADDRESS VARCHAR2(200 CHAR),
    ID VARCHAR2(40 CHAR) NOT NULL,
    PHOTO BLOB,
    ENABLE NUMBER(1) DEFAULT 1 NOT NULL,
    ISDELETE NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_WJLUSER PRIMARY KEY (USERNO)
);

CREATE TABLE PERMISSION(
    PERMISSIONNO VARCHAR2(40) NOT NULL,
    PERMISSIONNAME VARCHAR2(40 CHAR),
    CONSTRAINT PK_PERMISSION PRIMARY KEY (PERMISSIONNO)
);

CREATE TABLE USERPERMISSION(
    USERPERMISSIONNO VARCHAR2(40) NOT NULL,
    USERNO VARCHAR2(40) NOT NULL,
    PERMISSIONNO VARCHAR2(40) NOT NULL,
    READABLE NUMBER(1) DEFAULT 0,
    PERMISSIONEDIT NUMBER(1) DEFAULT 0,
    CONSTRAINT PK_USERPERMISSION PRIMARY KEY (USERPERMISSIONNO)
);

CREATE TABLE TEACHER(
    TEACHERNO VARCHAR2(40) NOT NULL,
    USERNO VARCHAR2(40) NOT NULL,
    TEACHERNAME VARCHAR2(40 CHAR),
    SKILL VARCHAR2(40 CHAR),
    DESCRIPTION CLOB, 
    TEACHERSTATUS NUMBER(1) DEFAULT 1,
    CONSTRAINT PK_TEACHER PRIMARY KEY (TEACHERNO)
);

CREATE TABLE EMPLOYEE(
    EMPNO VARCHAR2(40) NOT NULL,
    USERNO VARCHAR2(40) NOT NULL,
    EMPSTATUS NUMBER(1) DEFAULT 1,
    EMPNAME VARCHAR2(40 CHAR),
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EMPNO)
);

CREATE TABLE STUDENT(
    STUDENTNO VARCHAR2(40 BYTE) NOT NULL, 
	USERNO VARCHAR2(40 BYTE) NOT NULL, 
	BANJINO VARCHAR2(40 BYTE), 
	STUDENTNAME VARCHAR2(40 CHAR), 
	FACEID VARCHAR2(40 BYTE), 
	FACE BLOB, 
	STUDENTDESCRIPTION CLOB,
	STUDENTSTATUS NUMBER(10) DEFAULT 0,
    CONSTRAINT PK_STUDENT PRIMARY KEY (STUDENTNO) 
);

CREATE TABLE ChatRoom(
    chatRoomNo VARCHAR2(40 BYTE)  NOT NULL, 
	chatRoomName VARCHAR2(40 BYTE),
    chatRoomType NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_ChatRoom PRIMARY KEY (chatRoomNo)
);

CREATE TABLE ChatRoomMember(
    chatRoomMemberNo VARCHAR2(40 BYTE)  NOT NULL, 
	chatRoomNo VARCHAR2(40 BYTE) NOT NULL, 
    userNo VARCHAR2(40 BYTE) NOT NULL, 
	CONSTRAINT PK_ChatRoomMember PRIMARY KEY (chatRoomMemberNo)
);

CREATE TABLE Message(
    messageNo VARCHAR2(40 BYTE)  NOT NULL, 
	chatRoomNo VARCHAR2(40 BYTE) NOT NULL, 
	userNo VARCHAR2(40 BYTE)NOT NULL, 
	messageContent CLOB, 
	messageTime TIMESTAMP NOT NULL, 
	messageCount NUMBER(10) default 1, 	
    CONSTRAINT PK_Message PRIMARY KEY (messageNo)  
);

CREATE TABLE NOTIFY(
    NOTIFYNO VARCHAR2(40 BYTE)  NOT NULL, 
	USERNO VARCHAR2(40 BYTE) NOT NULL, 
	NOTIFYTYPE NUMBER(10)NOT NULL, 
	NOTIFYCONTENT CLOB, 
	NOTIFYDATE TIMESTAMP Not Null, 
    CONSTRAINT PK_NOTIFY PRIMARY KEY (NOTIFYNO)  
);

CREATE TABLE BASICCOURSE(
    BASICCOURSENO VARCHAR2(40) NOT NULL,
    BASICCOURSENAME VARCHAR2(40 CHAR) NOT NULL,
    BASICCOURSEINFO CLOB,
    LESSON NUMBER(10) DEFAULT 0 NOT NULL,
    ISDELETE NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_BASICCOURSE PRIMARY KEY(BASICCOURSENO)
);

CREATE TABLE BANJITYPECOURSE(
    BANJITYPECOURSENO VARCHAR2(40) NOT NULL,
    BANJITYPENO VARCHAR2(40) NOT NULL,
    BASICCOURSENO VARCHAR2(40) NOT NULL,
    CONSTRAINT PK_BANJITYPECOURSE PRIMARY KEY(BANJITYPECOURSENO)
);

CREATE TABLE BANJITYPE(
    BANJITYPENO VARCHAR2 (40 BYTE) NOT NULL,
    BANJITYPENAME VARCHAR2(40 CHAR) NOT NULL,
    CLASSHOURS NUMBER (10) NOT NULL,
    BANJITYPECONTENT CLOB,
    BANJITYPEENABLE NUMBER (1) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_BANJITYPE PRIMARY KEY (BANJITYPENO)
);

CREATE TABLE BANJI(
    BANJINO VARCHAR2 (40 BYTE)  NOT NULL,
    EMPNO VARCHAR2  (40 BYTE) NOT NULL,
    BANJITYPENO VARCHAR2 (40 BYTE) NOT NULL,
    STARTDAY DATE ,
    ENDDAY DATE ,
    BANJINAME VARCHAR2 (40 CHAR) NOT NULL,
    CLASSHOURS NUMBER (10) NOT NULL,
    NUMBEROFSTUDENT NUMBER (10) DEFAULT 0 NOT NULL,
    CLASSROOMNO VARCHAR2 (40 BYTE) NOT NULL,
    STATUS NUMBER (1) NOT NULL,
    BANJICONTENT CLOB,
    ISDELETE NUMBER (1) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_BANJI PRIMARY KEY (BANJINO)
);

CREATE TABLE BANJIPOST(
    BANJIPOSTNO VARCHAR2(40 BYTE) NOT NULL,
    BANJINO VARCHAR2(40 BYTE) NOT NULL,
    TITLE VARCHAR2(200 CHAR) NOT NULL,
    BANJIPOSTCONTENT CLOB,
    UPDATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    STATUS NUMBER(1) NOT NULL,
    CONSTRAINT PK_BANJIPOST PRIMARY KEY (BANJIPOSTNO)
);

CREATE TABLE FORUMTOPIC(
    FORUMTOPICNO VARCHAR2(40 BYTE) NOT NULL,
    BANJINO VARCHAR2(40 BYTE)NOT NULL,
    FORUMTOPICNAME VARCHAR2 (200 CHAR) NOT NULL,
    CONTENT CLOB,
    RULE CLOB,
    POSTTEMPLETE CLOB,
    ISDELETE NUMBER (1) DEFAULT (0) NOT NULL,
    CONSTRAINT PK_FORUMTOPIC PRIMARY KEY (FORUMTOPICNO)
);

CREATE TABLE FORUMPOST(
    FORUMPOSTNO VARCHAR2 (40 BYTE) NOT NULL,
    FORUMTOPICNO VARCHAR2 (40 BYTE) NOT NULL,
    STUDENTNO VARCHAR2 (40 BYTE) NOT NULL,
    TITLE VARCHAR2 (200 CHAR) NOT NULL,
    CONTENT CLOB ,
    UPDATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ISDELETE NUMBER (1) DEFAULT (0)NOT NULL,
    CONSTRAINT PK_FORUMPOST PRIMARY KEY (FORUMPOSTNO)
);

CREATE TABLE FORUMCOMMENT(
    FORUMCOMMENTNO VARCHAR2(40 BYTE) NOT NULL,
    FORUMPOSTNO VARCHAR2(40 BYTE)NOT NULL,
    STUDENTNO VARCHAR2 (40 BYTE) NOT NULL,
    CONTENT CLOB,
    UPDATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ISDELETE NUMBER (1) DEFAULT (0) NOT NULL,
    CONSTRAINT PK_FORUMCOMMENT PRIMARY KEY (FORUMCOMMENTNO)
);

CREATE TABLE REPORT(
    REPORTNO VARCHAR2(40 BYTE) NOT NULL,
    FORUMPOSTNO VARCHAR2(40 BYTE),
    FORUMCOMMENTNO VARCHAR2 (40 BYTE),
    STUDENTNO VARCHAR2 (40 BYTE) NOT NULL,
    TYPE NUMBER (10) NOT NULL,
    DESCRIPTION CLOB,
    REPORTTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    STATUS NUMBER (1) DEFAULT 0 NOT NULL, 
    CONSTRAINT PK_REPORT PRIMARY KEY (REPORTNO)
);

CREATE TABLE COURSE(
    COURSENO VARCHAR2(40) NOT NULL,
    BANJINO VARCHAR2(40) NOT NULL,
    TEACHERNO VARCHAR2(40) NOT NULL,
    CLASSROOMNO VARCHAR2(40) NOT NULL,
    BASICCOURSENO VARCHAR2(40) NOT NULL,
    COURSENAME VARCHAR2(40 CHAR) NOT NULL,
    COURSEOUTLINE CLOB,
    LESSON NUMBER(10) DEFAULT 0 NOT NULL ,
    STARTDATE DATE,
    ENDDATE DATE,
    STATUS NUMBER(1) DEFAULT 0 NOT NULL,
    ISDELETE NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_COURSE PRIMARY KEY(COURSENO)
);

CREATE TABLE COURSEPOST(
    COURSEPOSTNO VARCHAR2(40) NOT NULL,
    COURSENO VARCHAR2(40) NOT NULL,
    TITLE VARCHAR2(200 CHAR) NOT NULL,
    POSTCONTENT CLOB,
    UPDATETIME TIMESTAMP NOT NULL,
    CONSTRAINT PK_COURSEPOST PRIMARY KEY(COURSEPOSTNO)
);

CREATE TABLE TEACHINGPLAN(
    TEACHINGPLANNO VARCHAR2(40) NOT NULL,
    COURSENO VARCHAR2(40) NOT NULL,
    WEEK NUMBER(10) DEFAULT 0 NOT NULL,
    LESSON NUMBER(10) DEFAULT 0 NOT NULL,
    PLANCONTENT VARCHAR2(200 CHAR),
    CONSTRAINT PK_TEACHINGPLAN PRIMARY KEY(TEACHINGPLANNO)
);

CREATE TABLE FINALSCORE(
    FINALSCORENO VARCHAR2(40) NOT NULL,
    COURSENO VARCHAR2(40) NOT NULL,
    STUDENTNO VARCHAR2(40) NOT NULL,
    SCORE NUMBER(10) NOT NULL,
    CONSTRAINT PK_FINALSCORE PRIMARY KEY(FINALSCORENO)
);

CREATE TABLE COURSEASK(
    COURSEASKNO VARCHAR2(40) NOT NULL,
    COURSENO VARCHAR2(40) NOT NULL,
    STUDENTNO VARCHAR2(40) NOT NULL,
    TITLE VARCHAR2(200 CHAR) NOT NULL,
    QUESTION CLOB,
    UPDATETIME TIMESTAMP NOT NULL,
    STATUS NUMBER(1) DEFAULT 0 NOT NULL,
    ISDELETE NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_COURSEASK PRIMARY KEY(COURSEASKNO)
);

CREATE TABLE REPLY(
    REPLYNO VARCHAR2(40) NOT NULL,
    COURSEASKNO VARCHAR2(40) NOT NULL,
    TEACHERNO VARCHAR2(40),
    STUDENTNO VARCHAR2(40),
    REPLYCONTENT CLOB NOT NULL,
    UPDATETIME TIMESTAMP NOT NULL,
    CONSTRAINT PK_REPLY PRIMARY KEY(REPLYNO)
);

CREATE TABLE EVALUATION(
    EVALUATIONNO VARCHAR2(40) NOT NULL,
    COURSENO VARCHAR2(40) NOT NULL,
    STUDENTNO VARCHAR2(40) NOT NULL,
    QUESTION NUMBER(1) DEFAULT 0 NOT NULL,
    ANSWER NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_EVALUATION PRIMARY KEY(EVALUATIONNO)
);

CREATE TABLE CLASSROOM(
    CLASSROOMNO VARCHAR2(40) NOT NULL,
    CLASSROOMNAME VARCHAR2(40 CHAR),
    NUMBEROFSTUDENT NUMBER(10) NOT NULL,
    ISDELETE NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_CLASSROOM PRIMARY KEY(CLASSROOMNO)
);

CREATE TABLE TIMETABLE (
    TIMETABLENO VARCHAR2(40) NOT NULL,
    COURSENO VARCHAR2(40) NOT NULL,
    CLASSROOMNO VARCHAR2(40) NOT NULL,
    TIMETABLEPERIOD NUMBER(1) DEFAULT 0 , 
    TIMETABLEDATE DATE,
    TEACHINGLOG CLOB,
    ISDELETE NUMBER(1) DEFAULT 0 NOT NULL ,
    CONSTRAINT PK_TIMETABLE PRIMARY KEY (TIMETABLENO)
);

CREATE TABLE VIDEO(
    VIDEONO VARCHAR2(40) NOT NULL,
    TIMETABLENO VARCHAR2(40) NOT NULL,
    VIDEONAME VARCHAR2(40) NOT NULL,
    VIDEO BLOB,
    CONSTRAINT PK_VIDEO PRIMARY KEY (VIDEONO)
);

CREATE TABLE TEACHINGFILE (
    TEACHINGFILENO VARCHAR2(40) NOT NULL,
    TIMETABLENO VARCHAR2(40) NOT NULL,
    TEACHINGFILENAME VARCHAR2(40) NOT NULL,
    TEACHINGFILE BLOB,
    CONSTRAINT PK_TEACHINGFILE PRIMARY KEY (TEACHINGFILENO)
);

CREATE TABLE VIDEOLOG (
    VIDEOLOGNO VARCHAR2(40) NOT NULL,
    VIDEONO VARCHAR2(40) NOT NULL,
    WATCHTIME NUMBER(10),
    STATUS NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_VIDEOLOG PRIMARY KEY (VIDEOLOGNO)
);

CREATE TABLE LEAVE(
    LEAVENO VARCHAR2 (40 BYTE) NOT NULL,
    STUDENTNO VARCHAR2 (40 BYTE) NOT NULL,
    TIMETABLENO VARCHAR2 (40 BYTE) NOT NULL,
    TYPE NUMBER (1) DEFAULT 0 NOT NULL,
    DESCRIPTION VARCHAR2 (200 CHAR),
    STATUS NUMBER (1) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_LEAVE PRIMARY KEY (LEAVENO)
);

CREATE TABLE ATTENDANCE(
    ATTENDANCENO VARCHAR2 (40 BYTE) NOT NULL,
    STUDENTNO VARCHAR2 (40 BYTE) NOT NULL,
    TIMETABLENO VARCHAR2 (40 BYTE) NOT NULL,
    TIME TIMESTAMP,
    STATUS NUMBER (1) DEFAULT 0 NOT NULL,
    NOTE VARCHAR2 (200 CHAR),
    CONSTRAINT PK_ATTENDANCE PRIMARY KEY (ATTENDANCENO)
);

CREATE TABLE HEALTHLOG(
    HEALTHLOGNO VARCHAR2 (40 BYTE) NOT NULL,
    STUDENTNO VARCHAR2 (40 BYTE) NOT NULL,
    STATUS NUMBER (1) NOT NULL,
    HEALTHLOGDATE DATE DEFAULT CURRENT_DATE NOT NULL,
    CONSTRAINT PK_HEALTHLOG PRIMARY KEY (HEALTHLOGNO)
);
--------------------------------------------------------
--  Create SEQUENCE All
--------------------------------------------------------

CREATE SEQUENCE USER_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE PERMISSION_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE 
NOCYCLE
NOCACHE;

CREATE SEQUENCE USERPERMISSION_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE TEACHER_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE EMPLOYEE_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE STUDENTNO_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE ChatRoomNO_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE ChatRoomMemberNO_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE messageNo_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE NOTIFY_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE BANJI_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE BANJITYPE_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE BANJIPOST_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE BASICCOURSE_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE BANJITYPECOURSE_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE COURSE_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE COURSEPOST_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE TEACHINGPLAN_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE FINALSCORE_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE COURSEASK_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE REPLY_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE EVALUATION_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE CLASSROOM_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE TIMETABLE_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE TEACHINGFILE_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE VIDEO_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE VIDEOLOG_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE LEAVE_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE ATTENDANCE_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE HEALTHLOG_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE FORUMTOPIC_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE FORUMPOST_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE FORUMCOMMENT_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE REPORT_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;
--------------------------------------------------------
--  Create FK All
--------------------------------------------------------
ALTER TABLE USERPERMISSION ADD CONSTRAINT FK_USERPERMISSION_WJLUSER FOREIGN KEY (USERNO) REFERENCES WJLUSER(USERNO);
ALTER TABLE USERPERMISSION ADD CONSTRAINT FK_USERPERMISSION_PERMISSION FOREIGN KEY (PERMISSIONNO) REFERENCES PERMISSION(PERMISSIONNO);
ALTER TABLE TEACHER ADD CONSTRAINT FK_TEACHER_WJLUSER FOREIGN KEY(USERNO) REFERENCES WJLUSER(USERNO);
ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_EMPLOYEE_WJLUSER FOREIGN KEY(USERNO) REFERENCES WJLUSER(USERNO);
ALTER TABLE STUDENT ADD CONSTRAINT FK_STUDENT_BANJI FOREIGN KEY (BANJINO) REFERENCES BANJI(BANJINO);
ALTER TABLE STUDENT ADD CONSTRAINT FK_STUDENT_WJLUSER FOREIGN KEY(USERNO) REFERENCES WJLUSER(USERNO);
ALTER TABLE ChatRoomMember ADD CONSTRAINT FK_ChatRoomMember_chatRoom FOREIGN KEY (chatRoomNO) REFERENCES chatRoom(chatRoomNO);
ALTER TABLE ChatRoomMember ADD CONSTRAINT FK_ChatRoomMember_WJLUSER FOREIGN KEY(USERNO) REFERENCES WJLUSER(USERNO);
ALTER TABLE Message ADD CONSTRAINT FK_Message_chatRoom FOREIGN KEY (chatRoomNo) REFERENCES chatRoom(chatRoomNo);
ALTER TABLE Message ADD CONSTRAINT FK_Message_WJLUSER FOREIGN KEY(USERNO) REFERENCES WJLUSER(USERNO);
ALTER TABLE NOTIFY ADD CONSTRAINT FK_NOTIFY_WJLUSER FOREIGN KEY (USERNO) REFERENCES WJLUSER(USERNO);
ALTER TABLE BANJI ADD CONSTRAINT FK_BANJI_EMPLOYEE FOREIGN KEY (EMPNO) REFERENCES EMPLOYEE(EMPNO);
ALTER TABLE BANJI ADD CONSTRAINT FK_BANJI_BANJITYPE FOREIGN KEY (BANJITYPENO) REFERENCES BANJITYPE(BANJITYPENO);
ALTER TABLE BANJI ADD CONSTRAINT FK_BANJI_CLASSROOM FOREIGN KEY (CLASSROOMNO) REFERENCES CLASSROOM(CLASSROOMNO);
ALTER TABLE BANJIPOST ADD CONSTRAINT FK_BANJIPOST_BANJI FOREIGN KEY (BANJINO) REFERENCES BANJI(BANJINO);
ALTER TABLE FORUMTOPIC ADD CONSTRAINT FK_FORUMTOPIC_BANJI FOREIGN KEY(BANJINO) REFERENCES BANJI(BANJINO);
ALTER TABLE FORUMPOST ADD CONSTRAINT FK_FORUMPOST_FORUMTOPIC FOREIGN KEY(FORUMTOPICNO) REFERENCES FORUMTOPIC(FORUMTOPICNO);
ALTER TABLE FORUMPOST ADD CONSTRAINT FK_FORUMPOST_STUDENT FOREIGN KEY(STUDENTNO) REFERENCES STUDENT(STUDENTNO);
ALTER TABLE FORUMCOMMENT ADD CONSTRAINT FK_FORUMCOMMENT_FORUMPOST FOREIGN KEY(FORUMPOSTNO) REFERENCES FORUMPOST(FORUMPOSTNO);
ALTER TABLE FORUMCOMMENT ADD CONSTRAINT FK_FORUMCOMMENT_STUDENT FOREIGN KEY(STUDENTNO) REFERENCES STUDENT(STUDENTNO);
ALTER TABLE REPORT ADD CONSTRAINT FK_REPORT_FORUMPOST FOREIGN KEY(FORUMPOSTNO) REFERENCES FORUMPOST(FORUMPOSTNO);
ALTER TABLE REPORT ADD CONSTRAINT FK_REPORT_FORUMCOMMENT FOREIGN KEY(FORUMCOMMENTNO) REFERENCES FORUMCOMMENT(FORUMCOMMENTNO);
ALTER TABLE REPORT ADD CONSTRAINT FK_REPORT_STUDENT FOREIGN KEY(STUDENTNO) REFERENCES STUDENT(STUDENTNO);
ALTER TABLE BANJITYPECOURSE ADD CONSTRAINT FK_BANJITYPECOURSE_BASICCOURSE FOREIGN KEY(BASICCOURSENO) REFERENCES BASICCOURSE(BASICCOURSENO);
ALTER TABLE BANJITYPECOURSE ADD CONSTRAINT FK_BANJITYPECOURSE_BANJITYPE FOREIGN KEY(BANJITYPENO) REFERENCES BANJITYPE(BANJITYPENO);
ALTER TABLE COURSE ADD CONSTRAINT FK_COURSE_BANJI FOREIGN KEY(BANJINO) REFERENCES BANJI(BANJINO);
ALTER TABLE COURSE ADD CONSTRAINT FK_COURSE_TEACHER FOREIGN KEY(TEACHERNO) REFERENCES TEACHER(TEACHERNO);
ALTER TABLE COURSE ADD CONSTRAINT FK_COURSE_CLASSROOM FOREIGN KEY(CLASSROOMNO) REFERENCES CLASSROOM(CLASSROOMNO);
ALTER TABLE COURSE ADD CONSTRAINT FK_COURSE_BASICCOURSE FOREIGN KEY(BASICCOURSENO) REFERENCES BASICCOURSE(BASICCOURSENO);
ALTER TABLE COURSEPOST ADD CONSTRAINT FK_COURSEPOST_COURSE FOREIGN KEY(COURSENO) REFERENCES COURSE(COURSENO);
ALTER TABLE TEACHINGPLAN ADD CONSTRAINT FK_TEACHINGPLAN_COURSE FOREIGN KEY(COURSENO) REFERENCES COURSE(COURSENO);
ALTER TABLE FINALSCORE ADD CONSTRAINT FK_FINALSCORE_COURSE FOREIGN KEY(COURSENO) REFERENCES COURSE(COURSENO);
ALTER TABLE FINALSCORE ADD CONSTRAINT FK_FINALSCORE_STUDENT FOREIGN KEY(STUDENTNO) REFERENCES STUDENT(STUDENTNO);
ALTER TABLE COURSEASK ADD CONSTRAINT FK_COURSEASK_COURSE FOREIGN KEY(COURSENO) REFERENCES COURSE(COURSENO);
ALTER TABLE COURSEASK ADD CONSTRAINT FK_COURSEASK_STUDENT FOREIGN KEY(STUDENTNO) REFERENCES STUDENT(STUDENTNO);
ALTER TABLE REPLY ADD CONSTRAINT FK_REPLY_COURSEASK FOREIGN KEY(COURSEASKNO) REFERENCES COURSEASK(COURSEASKNO);
ALTER TABLE REPLY ADD CONSTRAINT FK_REPLY_TEACHER FOREIGN KEY(TEACHERNO) REFERENCES TEACHER(TEACHERNO);
ALTER TABLE REPLY ADD CONSTRAINT FK_REPLY_STUDENT FOREIGN KEY(STUDENTNO) REFERENCES STUDENT(STUDENTNO);
ALTER TABLE EVALUATION ADD CONSTRAINT FK_EVALUATION_COURSE FOREIGN KEY(COURSENO) REFERENCES COURSE(COURSENO);
ALTER TABLE EVALUATION ADD CONSTRAINT FK_EVALUATION_STUDENT FOREIGN KEY(STUDENTNO) REFERENCES STUDENT(STUDENTNO);
ALTER TABLE TIMETABLE ADD CONSTRAINT FK_TIMETABLE_COURSE FOREIGN KEY (COURSENO) REFERENCES COURSE(COURSENO);
ALTER TABLE TIMETABLE ADD CONSTRAINT FK_TIMETABLE_CLASSROOM FOREIGN KEY (CLASSROOMNO) REFERENCES CLASSROOM(CLASSROOMNO); 
ALTER TABLE VIDEO ADD CONSTRAINT FK_VIDEO_TIMETABLE FOREIGN KEY (TIMETABLENO) REFERENCES TIMETABLE(TIMETABLENO);
ALTER TABLE TEACHINGFILE ADD CONSTRAINT FK_TEACHINGFILE_TIMETABLE FOREIGN KEY (TIMETABLENO) REFERENCES TIMETABLE(TIMETABLENO);
ALTER TABLE VIDEOLOG ADD CONSTRAINT FK_VIDEOLOG_VIDEO FOREIGN KEY (VIDEONO) REFERENCES VIDEO(VIDEONO);
ALTER TABLE LEAVE ADD CONSTRAINT FK_LEAVE_STUDENT FOREIGN KEY(STUDENTNO) REFERENCES STUDENT(STUDENTNO);
ALTER TABLE LEAVE ADD CONSTRAINT FK_LEAVE_TIMETABLE FOREIGN KEY (TIMETABLENO) REFERENCES TIMETABLE(TIMETABLENO);
ALTER TABLE ATTENDANCE ADD CONSTRAINT FK_ATTENDANCE_STUDENT FOREIGN KEY (STUDENTNO) REFERENCES STUDENT(STUDENTNO);
ALTER TABLE ATTENDANCE ADD CONSTRAINT FK_ATTENDANCE_TIMETABLE FOREIGN KEY (TIMETABLENO) REFERENCES TIMETABLE(TIMETABLENO);
ALTER TABLE HEALTHLOG ADD CONSTRAINT FK_HEALTHLOG_STUDENT FOREIGN KEY (STUDENTNO) REFERENCES STUDENT(STUDENTNO);
--------------------------------------------------------
--  Insert into 使用者 WJLUSER
--------------------------------------------------------
Insert into WJLUSER (USERNO,ACCOUNT,PASSWORD,TYPE,NAME,MAIL,PHONE,ADDRESS,ID,ENABLE,ISDELETE) values ('U'||LPAD(to_char(USER_SEQ.NEXTVAL), '6', '0'),'dirtybird85','dirtybird115',2,'陳念群','birdfly@gmail.com','0988874521','新竹縣湖口鄉中正七街189號','J104239444',1,0);
Insert into WJLUSER (USERNO,ACCOUNT,PASSWORD,TYPE,NAME,MAIL,PHONE,ADDRESS,ID,ENABLE,ISDELETE) values ('U'||LPAD(to_char(USER_SEQ.NEXTVAL), '6', '0'),'asusbro14','asusbro1414',2,'馮飴杰','asusbro@gmail.com','0914562257','新竹縣湖口鄉德美路61巷16號','J185755861',1,0);
Insert into WJLUSER (USERNO,ACCOUNT,PASSWORD,TYPE,NAME,MAIL,PHONE,ADDRESS,ID,ENABLE,ISDELETE) values ('U'||LPAD(to_char(USER_SEQ.NEXTVAL), '6', '0'),'linn3636','linn55n89',2,'林彥義','linyan996@gmail.com','0984456339','苗栗縣苗栗市建台街1巷13號','P201929205',0,0);
Insert into WJLUSER (USERNO,ACCOUNT,PASSWORD,TYPE,NAME,MAIL,PHONE,ADDRESS,ID,ENABLE,ISDELETE) values ('U'||LPAD(to_char(USER_SEQ.NEXTVAL), '6', '0'),'rich2000','rich2000',1,'吳冠宏','qdzcea@gmail.com','0954652187','彰化縣彰化市新生路97巷2號','U168651372',1,0);
Insert into WJLUSER (USERNO,ACCOUNT,PASSWORD,TYPE,NAME,MAIL,PHONE,ADDRESS,ID,ENABLE,ISDELETE) values ('U'||LPAD(to_char(USER_SEQ.NEXTVAL), '6', '0'),'qweasdzxc87','qweasdzxc2546',1,'程淑芬','chenhowe@yahoo.com.tw','0911195632','基隆市中正區義一路1號','C253617614',0,0);
Insert into WJLUSER (USERNO,ACCOUNT,PASSWORD,TYPE,NAME,MAIL,PHONE,ADDRESS,ID,ENABLE,ISDELETE) values ('U'||LPAD(to_char(USER_SEQ.NEXTVAL), '6', '0'),'ttf9889','wangchenn',1,'陳宇翔','oochang96@gmail.com','0999856321','新北市林口區粉寮路一段21號1樓','F143989355',1,0);
INSERT INTO WJLUSER (USERNO,ACCOUNT,PASSWORD,TYPE,NAME,MAIL,PHONE,ADDRESS,ID,ENABLE,ISDELETE) VALUES ('U'||LPAD(to_char(USER_SEQ.NEXTVAL), '6', '0'),'chen8601','chen8601',0,'陳浩偉','yymm55680@gmail.com','0988603000','新竹市北區榮濱路19巷16號','J130173079',1,0);
Insert into WJLUSER (USERNO,ACCOUNT,PASSWORD,TYPE,NAME,MAIL,PHONE,ADDRESS,ID,ENABLE,ISDELETE) values ('U'||LPAD(to_char(USER_SEQ.NEXTVAL), '6', '0'),'issue86','issue86',0,'陳怡秀','ea1030014@gmail.com','0977887878','台北市三重區三路里96號','A194725855',1,0);
Insert into WJLUSER (USERNO,ACCOUNT,PASSWORD,TYPE,NAME,MAIL,PHONE,ADDRESS,ID,ENABLE,ISDELETE) values ('U'||LPAD(to_char(USER_SEQ.NEXTVAL), '6', '0'),'getout332','getout332',0,'陳開炫','getout332@gmail.com','0998541254','台北市信義區松仁路97號','A171922472',1,0);
--------------------------------------------------------
--  Insert into 通知 notify
--------------------------------------------------------
INSERT INTO notify (notifyno,userno,notifytype,notifycontent,notifydate) VALUES (NOTIFY_SEQ.nextval,'U000007',1,'請記得補簽',TO_TIMESTAMP('2020-09-25 09:20:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO notify (notifyno,userno,notifytype,notifycontent,notifydate) VALUES (NOTIFY_SEQ.nextval,'U000001',1,'有新的請假申請',TO_TIMESTAMP('2020-09-25 15:20:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO notify (notifyno,userno,notifytype,notifycontent,notifydate) VALUES (NOTIFY_SEQ.nextval,'U000008',2,'您在影片區的發問已被回覆',TO_TIMESTAMP('2020-09-26 18:45:00','YYYY-MM-DD HH24:MI:SS'));
--------------------------------------------------------
--  Insert into 權限 PERMISSION
--------------------------------------------------------
INSERT INTO PERMISSION(PERMISSIONNO,PERMISSIONNAME) VALUES (PERMISSION_SEQ.nextval,'編輯班種');
Insert into PERMISSION(PERMISSIONNO,PERMISSIONNAME) values (PERMISSION_SEQ.NEXTVAL,'編輯教室');
Insert into PERMISSION(PERMISSIONNO,PERMISSIONNAME) values (PERMISSION_SEQ.NEXTVAL,'請假審核');
--------------------------------------------------------
--  Insert into 使用者權限 USERPERMISSION
--------------------------------------------------------
INSERT INTO USERPERMISSION(USERPERMISSIONNO,USERNO,PERMISSIONNO,READABLE,PERMISSIONEDIT) VALUES (USERPERMISSION_SEQ.NEXTVAL,'U000001','1',1,1);
INSERT INTO USERPERMISSION(USERPERMISSIONNO,USERNO,PERMISSIONNO,READABLE,PERMISSIONEDIT) VALUES (USERPERMISSION_SEQ.NEXTVAL,'U000001','2',1,1);
INSERT INTO USERPERMISSION(USERPERMISSIONNO,USERNO,PERMISSIONNO,READABLE,PERMISSIONEDIT) VALUES (USERPERMISSION_SEQ.NEXTVAL,'U000001','3',1,1);
INSERT INTO USERPERMISSION(USERPERMISSIONNO,USERNO,PERMISSIONNO,READABLE,PERMISSIONEDIT) VALUES (USERPERMISSION_SEQ.NEXTVAL,'U000002','1',1,1);
INSERT INTO USERPERMISSION(USERPERMISSIONNO,USERNO,PERMISSIONNO,READABLE,PERMISSIONEDIT) VALUES (USERPERMISSION_SEQ.NEXTVAL,'U000002','2',1,1);
INSERT INTO USERPERMISSION(USERPERMISSIONNO,USERNO,PERMISSIONNO,READABLE,PERMISSIONEDIT) VALUES (USERPERMISSION_SEQ.NEXTVAL,'U000002','3',1,1);
INSERT INTO USERPERMISSION(USERPERMISSIONNO,USERNO,PERMISSIONNO,READABLE,PERMISSIONEDIT) VALUES (USERPERMISSION_SEQ.NEXTVAL,'U000003','1',1,0);
INSERT INTO USERPERMISSION(USERPERMISSIONNO,USERNO,PERMISSIONNO,READABLE,PERMISSIONEDIT) VALUES (USERPERMISSION_SEQ.NEXTVAL,'U000003','2',1,0);
INSERT INTO USERPERMISSION(USERPERMISSIONNO,USERNO,PERMISSIONNO,READABLE,PERMISSIONEDIT) VALUES (USERPERMISSION_SEQ.NEXTVAL,'U000003','3',1,0);
--------------------------------------------------------
--  Insert into 聊天室 chatroom
--------------------------------------------------------
INSERT INTO chatroom (chatroomno,chatroomname,chatRoomType) VALUES (CHATROOMNO_SEQ.nextval,'GROUP6',1);
INSERT INTO chatroom (chatroomno,chatroomname,chatRoomType) VALUES (CHATROOMNO_SEQ.nextval,null,0);
INSERT INTO chatroom (chatroomno,chatroomname,chatRoomType) VALUES (CHATROOMNO_SEQ.nextval,null,0);
--------------------------------------------------------
--  Insert into 聊天室成員 chatroommember
--------------------------------------------------------
INSERT INTO chatroommember (chatroommemberno,chatroomno,userno) VALUES (CHATROOMMEMBERNO_SEQ.nextval,'1','U000007');
INSERT INTO chatroommember (chatroommemberno,chatroomno,userno) VALUES (CHATROOMMEMBERNO_SEQ.nextval,'1','U000008');
INSERT INTO chatroommember (chatroommemberno,chatroomno,userno) VALUES (CHATROOMMEMBERNO_SEQ.nextval,'1','U000009');
INSERT INTO chatroommember (chatroommemberno,chatroomno,userno) VALUES (CHATROOMMEMBERNO_SEQ.nextval,'2','U000007');
INSERT INTO chatroommember (chatroommemberno,chatroomno,userno) VALUES (CHATROOMMEMBERNO_SEQ.nextval,'2','U000008');
INSERT INTO chatroommember (chatroommemberno,chatroomno,userno) VALUES (CHATROOMMEMBERNO_SEQ.nextval,'3','U000007');
INSERT INTO chatroommember (chatroommemberno,chatroomno,userno) VALUES (CHATROOMMEMBERNO_SEQ.nextval,'3','U000009');
--------------------------------------------------------
--  Insert into 訊息 message
--------------------------------------------------------
INSERT INTO message (messageno,chatroomno,userno,messagecontent,messagetime) VALUES (MESSAGENO_SEQ.nextval,'1','U000007','第六組的各位，大家好!',to_timestamp('2020-09-20 20:01:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO message (messageno,chatroomno,userno,messagecontent,messagetime) VALUES (MESSAGENO_SEQ.nextval,'2','U000007','明天中午吃什麼',to_timestamp('2020-09-20 20:25:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO message (messageno,chatroomno,userno,messagecontent,messagetime) VALUES (MESSAGENO_SEQ.nextval,'3','U000007','明天中午要一起吃飯嗎',to_timestamp('2020-09-20 20:30:00','YYYY-MM-DD HH24:MI:SS'));
--------------------------------------------------------
--  Insert into 導師 EMPLOYEE
--------------------------------------------------------
INSERT INTO EMPLOYEE(EMPNO,USERNO,EMPSTATUS,EMPNAME) VALUES('E'||LPAD(to_char(EMPLOYEE_SEQ.NEXTVAL), '6', '0'),'U000001',1,'陳念群');
INSERT INTO EMPLOYEE(EMPNO,USERNO,EMPSTATUS,EMPNAME) VALUES('E'||LPAD(to_char(EMPLOYEE_SEQ.NEXTVAL), '6', '0'),'U000002',1,'馮飴杰');
INSERT INTO EMPLOYEE(EMPNO,USERNO,EMPSTATUS,EMPNAME) VALUES('E'||LPAD(to_char(EMPLOYEE_SEQ.NEXTVAL), '6', '0'),'U000003',2,'林彥義');
--------------------------------------------------------
--  Insert into 講師 TEACHER
--------------------------------------------------------
INSERT INTO TEACHER(TEACHERNO,USERNO,TEACHERNAME,SKILL,DESCRIPTION,TEACHERSTATUS) VALUES('T'||LPAD(to_char(TEACHER_SEQ.NEXTVAL), '6', '0'),'U000004','吳冠宏','Java','深得「吳神」肯定的新一代明星講師，總能用有趣簡單的方式讓學員進入門檻，深具耐心，對學員專題悉心指導與陪伴，學員評價超優。',1);
INSERT INTO TEACHER(TEACHERNO,USERNO,TEACHERNAME,SKILL,DESCRIPTION,TEACHERSTATUS) VALUES('T'||LPAD(to_char(TEACHER_SEQ.NEXTVAL), '6', '0'),'U000005','程淑芬','區塊鏈','數據科學家、區塊鏈與虛擬貨幣專家。擁有加密貨幣造幣技術、錢包軟體研發、智能合約開發及挖礦與礦池聯合挖礦自有技術。',2);
INSERT INTO TEACHER(TEACHERNO,USERNO,TEACHERNAME,SKILL,DESCRIPTION,TEACHERSTATUS) VALUES('T'||LPAD(to_char(TEACHER_SEQ.NEXTVAL), '6', '0'),'U000006','陳宇翔','雲端技術','網路口碑超高！具備數十年JAVA教學經驗，擅長Java物件導向、進階程式設計、Java Web應用系統、關聯式資料庫系統分析與設計',1);
--------------------------------------------------------
--  Insert into 班種 banjitype
--------------------------------------------------------
INSERT INTO banjitype (banjitypeno,banjitypename,classhours,banjitypecontent,banjitypeenable) VALUES ('BT'||LPAD(to_char(BANJITYPE_SEQ.NEXTVAL), '3', '0'),'Java養成班',600,'Java養成班...etc',1);
INSERT INTO banjitype (banjitypeno,banjitypename,classhours,banjitypecontent,banjitypeenable) VALUES ('BT'||LPAD(to_char(BANJITYPE_SEQ.NEXTVAL), '3', '0'),'雲端網路系統工程師養成班',600,'雲端網路系統工程師養成班.....雲端服務具備延展性、流動性和靈活應變等特質，能有效增加企業營運彈性與降低成本。',1);
INSERT INTO banjitype (banjitypeno,banjitypename,classhours,banjitypecontent,banjitypeenable) VALUES ('BT'||LPAD(to_char(BANJITYPE_SEQ.NEXTVAL), '3', '0'),'AI/BigData資料分析師養成班',600,'AI/Big Data資料分析師養成班....現今最夯AIOT(人工智慧+物聯網)、FinTech(金融科技)、工業4.0、商業趨勢分析、智慧製造與自駕車技術等，都是「AI人工智慧」與「Big Data大數據」所引爆的潮流',1);
--------------------------------------------------------
--  Insert into 基本課程 basiccourse
--------------------------------------------------------
INSERT INTO basiccourse (basiccourseno,basiccoursename,basiccourseinfo,lesson,isdelete) VALUES ('BC'||LPAD(to_char(BASICCOURSE_SEQ.NEXTVAL), '3', '0'),'JDBC','Java資料庫連接，（Java Database Connectivity，簡稱JDBC）是Java語言中用來規範客戶端程式如何來存取資料庫的應用程式介面。',10,0);
INSERT INTO basiccourse (basiccourseno,basiccoursename,basiccourseinfo,lesson,isdelete) VALUES ('BC'||LPAD(to_char(BASICCOURSE_SEQ.NEXTVAL), '3', '0'),'JAVA','Java是一種廣泛使用的電腦程式設計語言，擁有跨平台、物件導向、泛型程式設計的特性，廣泛應用於企業級Web應用開發和行動應用開發。',20,0);
INSERT INTO basiccourse (basiccourseno,basiccoursename,basiccourseinfo,lesson,isdelete) VALUES ('BC'||LPAD(to_char(BASICCOURSE_SEQ.NEXTVAL), '3', '0'),'SERVLET','Servlet（Server Applet），全稱Java Servlet。 是用Java編寫的伺服器端程式。 其主要功能在於互動式地瀏覽和修改資料，生成動態Web內容。',30,0);
--------------------------------------------------------
--  Insert into 班種課程 banjitypecourse
--------------------------------------------------------
INSERT INTO banjitypecourse (banjitypecourseno,banjitypeno,basiccourseno) VALUES (BANJITYPECOURSE_SEQ.nextval,'BT001','BC001');
INSERT INTO banjitypecourse (banjitypecourseno,banjitypeno,basiccourseno) VALUES (BANJITYPECOURSE_SEQ.nextval,'BT002','BC002');
INSERT INTO banjitypecourse (banjitypecourseno,banjitypeno,basiccourseno) VALUES (BANJITYPECOURSE_SEQ.nextval,'BT003','BC003');
--------------------------------------------------------
--  Insert into 教室 classroom
--------------------------------------------------------
INSERT INTO classroom (classroomno,classroomname,numberofstudent,isdelete) VALUES (CLASSROOM_SEQ.nextval,'204',60,0);
INSERT INTO classroom (classroomno,classroomname,numberofstudent,isdelete) VALUES (CLASSROOM_SEQ.nextval,'203',60,0);
INSERT INTO classroom (classroomno,classroomname,numberofstudent,isdelete) VALUES (CLASSROOM_SEQ.nextval,'202',60,0);
--------------------------------------------------------
--  Insert into 班級 banji
--------------------------------------------------------
INSERT INTO banji (banjino,empno,banjitypeno,startday,endday,banjiname,classhours,numberofstudent,classroomno,status,banjicontent,isdelete) VALUES ('B'||LPAD(to_char(BANJI_SEQ.NEXTVAL), '3', '0'),'E000001','BT001',TO_DATE('2020-06-02','YYYY-MM-DD'),TO_DATE('2020-11-12','YYYY-MM-DD'),'EA103',600,60,'1',1,'EA103...etc',0);
INSERT INTO banji (banjino,empno,banjitypeno,startday,endday,banjiname,classhours,numberofstudent,classroomno,status,banjicontent,isdelete) VALUES ('B'||LPAD(to_char(BANJI_SEQ.NEXTVAL), '3', '0'),'E000002','BT002',TO_DATE('2020-09-28','YYYY-MM-DD'),TO_DATE('2021-03-05','YYYY-MM-DD'),'AD101',600,60,'1',1,'AD101...etc',0);
INSERT INTO banji (banjino,empno,banjitypeno,startday,endday,banjiname,classhours,numberofstudent,classroomno,status,banjicontent,isdelete) VALUES ('B'||LPAD(to_char(BANJI_SEQ.NEXTVAL), '3', '0'),'E000003','BT003',TO_DATE('2020-10-27','YYYY-MM-DD'),TO_DATE('2021-04-29','YYYY-MM-DD'),'BG105',600,60,'1',1,'BG105...etc',0);
--------------------------------------------------------
--  Insert into 班級公告 banjipost
--------------------------------------------------------
INSERT INTO banjipost (banjipostno,banjino,title,banjipostcontent,updatetime,status) VALUES (BANJIPOST_SEQ.nextval,'B001','夜輔未簽到同學請補簽','夜輔未簽到同學請補簽...etc',to_timestamp('2020-09-24 20:00:00','YYYY-MM-DD HH24:MI:SS'),0);
INSERT INTO banjipost (banjipostno,banjino,title,banjipostcontent,updatetime,status) VALUES (BANJIPOST_SEQ.nextval,'B002','上課同學請繳交作業','未繳交作業的同學請趕緊上傳...etc',to_timestamp('2020-10-14 08:00:00','YYYY-MM-DD HH24:MI:SS'),0);
INSERT INTO banjipost (banjipostno,banjino,title,banjipostcontent,updatetime,status) VALUES (BANJIPOST_SEQ.nextval,'B003','上課時請到櫃檯拿書','請有空同學至櫃檯拿書...etc',to_timestamp('2020-11-24 12:00:00','YYYY-MM-DD HH24:MI:SS'),0);
--------------------------------------------------------
--  Insert into 學員 student
--------------------------------------------------------
INSERT INTO student (studentno,userno,banjino,studentname,faceid,studentdescription,studentstatus) VALUES ('S'||LPAD(to_char(STUDENTNO_SEQ.NEXTVAL), '6', '0'),'U000007','B001','陳浩偉','1', '大家好，我是9都蘭吳青峰',1);
INSERT INTO student (studentno,userno,banjino,studentname,faceid,studentdescription,studentstatus) VALUES ('S'||LPAD(to_char(STUDENTNO_SEQ.NEXTVAL), '6', '0'),'U000008','B001','陳怡秀','2', 'Hello every one. My name is Issue',1);
INSERT INTO student (studentno,userno,banjino,studentname,faceid,studentdescription,studentstatus) VALUES ('S'||LPAD(to_char(STUDENTNO_SEQ.NEXTVAL), '6', '0'),'U000009','B001','陳開炫','3', 'Jason JSON 被收購的JASON超市',1);
--------------------------------------------------------
--  Insert into 討論區主題 forumtopic
--------------------------------------------------------
INSERT INTO forumtopic (forumtopicno,banjino,forumtopicname,content,rule,posttemplete,isdelete) VALUES (FORUMTOPIC_SEQ.nextval,'B001','學術版','閒聊版...etc','閒聊版-版規...etc','閒聊版-發文樣板...etc',0);
INSERT INTO forumtopic (forumtopicno,banjino,forumtopicname,content,rule,posttemplete,isdelete) VALUES (FORUMTOPIC_SEQ.nextval,'B001','運動版','揪團跑步','嚴禁色情暴力言語霸凌等字言','運動版-發文樣板(請照格式發文)',0);
INSERT INTO forumtopic (forumtopicno,banjino,forumtopicname,content,rule,posttemplete,isdelete) VALUES (FORUMTOPIC_SEQ.nextval,'B001','閒聊版','JS語法疑問','嚴禁色情暴力言語霸凌等字言','學術版-發文樣板(請照格式發文)',0);
--------------------------------------------------------
--  Insert into 討論區發文 forumpost
--------------------------------------------------------
INSERT INTO forumpost (forumpostno,forumtopicno,studentno,title,content,updatetime,createtime,isdelete) VALUES (FORUMPOST_SEQ.nextval,'1','S000001','Hello Java','Hello Java的code怎麼打',to_timestamp('2020-09-24 15:00:00','YYYY-MM-DD HH24:MI:SS'),to_timestamp('2020-09-23 20:20:20','YYYY-MM-DD HH24:MI:SS'),0);
INSERT INTO forumpost (forumpostno,forumtopicno,studentno,title,content,updatetime,createtime,isdelete) VALUES (FORUMPOST_SEQ.nextval,'2','S000002','今日約跑','晚上10點學校操場',to_timestamp('2020-09-26 16:00:00','YYYY-MM-DD HH24:MI:SS'),to_timestamp('2020-09-24 21:20:20','YYYY-MM-DD HH24:MI:SS'),0);
INSERT INTO forumpost (forumpostno,forumtopicno,studentno,title,content,updatetime,createtime,isdelete) VALUES (FORUMPOST_SEQ.nextval,'3','S000003','下課吃竹香','Frank說要請客',to_timestamp('2020-09-27 18:00:00','YYYY-MM-DD HH24:MI:SS'),to_timestamp('2020-09-24 22:20:20','YYYY-MM-DD HH24:MI:SS'),0);
--------------------------------------------------------
--  Insert into 發文留言 forumcomment
--------------------------------------------------------
INSERT INTO forumcomment (forumcommentno,forumpostno,studentno,content,updatetime,createtime,isdelete) VALUES (FORUMCOMMENT_SEQ.nextval,'1','S000001','自己的發文自己留言',to_timestamp('2020-09-24 09:01:00','YYYY-MM-DD HH24:MI:SS'),to_timestamp('2020-09-23 23:01:00','YYYY-MM-DD HH24:MI:SS'),0);
INSERT INTO forumcomment (forumcommentno,forumpostno,studentno,content,updatetime,createtime,isdelete) VALUES (FORUMCOMMENT_SEQ.nextval,'2','S000002','浩偉確實是到此一遊',to_timestamp('2020-09-25 09:31:00','YYYY-MM-DD HH24:MI:SS'),to_timestamp('2020-09-22 03:01:00','YYYY-MM-DD HH24:MI:SS'),0);
INSERT INTO forumcomment (forumcommentno,forumpostno,studentno,content,updatetime,createtime,isdelete) VALUES (FORUMCOMMENT_SEQ.nextval,'3','S000003','我就胖不服來辯',to_timestamp('2020-09-26 19:01:00','YYYY-MM-DD HH24:MI:SS'),to_timestamp('2020-09-22 20:01:00','YYYY-MM-DD HH24:MI:SS'),0);
--------------------------------------------------------
--  Insert into 檢舉 report
--------------------------------------------------------
INSERT INTO report (reportno,forumpostno,forumcommentno,studentno,type,description,reporttime,status) VALUES (REPORT_SEQ.nextval,'1',null,'S000001',1,'自己的貼文自己檢舉',to_timestamp('2020-09-25 11:11:11','YYYY-MM-DD HH24:MI:SS'),0);
INSERT INTO report (reportno,forumpostno,forumcommentno,studentno,type,description,reporttime,status) VALUES (REPORT_SEQ.nextval,'2',null,'S000002',1,'內容不實',to_timestamp('2020-09-26 01:11:11','YYYY-MM-DD HH24:MI:SS'),0);
INSERT INTO report (reportno,forumpostno,forumcommentno,studentno,type,description,reporttime,status) VALUES (REPORT_SEQ.nextval,null,'3','S000003',1,'內容已涉及人身攻擊',to_timestamp('2020-09-27 21:11:11','YYYY-MM-DD HH24:MI:SS'),0);
--------------------------------------------------------
--  Insert into 課程 course
--------------------------------------------------------
INSERT INTO course (courseno,banjino,teacherno,classroomno,basiccourseno,coursename,courseoutline,lesson,startdate,enddate,status,isdelete) VALUES ('C'||LPAD(to_char(COURSE_SEQ.NEXTVAL), '3', '0'),'B001','T000001','1','BC001','JDBC','Java資料庫連接，（Java Database Connectivity，簡稱JDBC）是Java語言中用來規範客戶端程式如何來存取資料庫的應用程式介面。',10,TO_DATE('2020-07-01','YYYY-MM-DD'),TO_DATE('2020-07-05','YYYY-MM-DD'),2,0);
INSERT INTO course (courseno,banjino,teacherno,classroomno,basiccourseno,coursename,courseoutline,lesson,startdate,enddate,status,isdelete) VALUES ('C'||LPAD(to_char(COURSE_SEQ.NEXTVAL), '3', '0'),'B001','T000001','1','BC002','JAVA','Java是一種廣泛使用的電腦程式設計語言，擁有跨平台、物件導向、泛型程式設計的特性，廣泛應用於企業級Web應用開發和行動應用開發。',20,TO_DATE('2020-09-05','YYYY-MM-DD'),TO_DATE('2020-10-05','YYYY-MM-DD'),1,0);
INSERT INTO course (courseno,banjino,teacherno,classroomno,basiccourseno,coursename,courseoutline,lesson,startdate,enddate,status,isdelete) VALUES ('C'||LPAD(to_char(COURSE_SEQ.NEXTVAL), '3', '0'),'B001','T000002','1','BC003','SERVLET','Servlet（Server Applet），全稱Java Servlet。 是用Java編寫的伺服器端程式。 其主要功能在於互動式地瀏覽和修改資料，生成動態Web內容。',30,TO_DATE('2020-10-06','YYYY-MM-DD'),TO_DATE('2020-11-05','YYYY-MM-DD'),0,0);
--------------------------------------------------------
--  Insert into 課程公告 coursepost
--------------------------------------------------------
INSERT INTO coursepost (coursepostno,courseno,title,postcontent,updatetime) VALUES (COURSEPOST_SEQ.nextval,'C001','JDBC線上考試','JDBC線上考試，考試範圍1-4章',to_timestamp('2020-07-03 09:01:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO coursepost (coursepostno,courseno,title,postcontent,updatetime) VALUES (COURSEPOST_SEQ.nextval,'C002','JAVA線上考試','JAVA線上考試，考試範圍5-8章',to_timestamp('2020-08-03 10:01:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO coursepost (coursepostno,courseno,title,postcontent,updatetime) VALUES (COURSEPOST_SEQ.nextval,'C003','SERVLET線上考試','SERVLET線上考試，考試範圍1-10章',to_timestamp('2020-09-03 11:01:00','YYYY-MM-DD HH24:MI:SS'));
--------------------------------------------------------
--  Insert into 教學計畫 teachingplan
--------------------------------------------------------
INSERT INTO teachingplan (teachingplanno,courseno,week,lesson,plancontent) VALUES (TEACHINGPLAN_SEQ.nextval,'C001','1',1,'JDBC概論...etc');
INSERT INTO teachingplan (teachingplanno,courseno,week,lesson,plancontent) VALUES (TEACHINGPLAN_SEQ.nextval,'C001','2',2,'JDBC環境設置...etc');
INSERT INTO teachingplan (teachingplanno,courseno,week,lesson,plancontent) VALUES (TEACHINGPLAN_SEQ.nextval,'C001','3',3,'JDBC SQL語法...etc');
--------------------------------------------------------
--  Insert into 教學評鑑 evaluation
--------------------------------------------------------
INSERT INTO evaluation (evaluationno, courseno, studentno, question, answer) VALUES (EVALUATION_SEQ.nextval, 'C001', 'S000001', 1, 9);
INSERT INTO evaluation (evaluationno, courseno, studentno, question, answer) VALUES (EVALUATION_SEQ.nextval, 'C001', 'S000002', 2, 8);
INSERT INTO evaluation (evaluationno, courseno, studentno, question, answer) VALUES (EVALUATION_SEQ.nextval, 'C001', 'S000003', 3, 7);
--------------------------------------------------------
--  Insert into 期末成績 finalscore
--------------------------------------------------------
INSERT INTO finalscore (finalscoreno,courseno,studentno,score) VALUES (FINALSCORE_SEQ.nextval,'C001','S000001',90);
INSERT INTO finalscore (finalscoreno,courseno,studentno,score) VALUES (FINALSCORE_SEQ.nextval,'C001','S000002',80);
INSERT INTO finalscore (finalscoreno,courseno,studentno,score) VALUES (FINALSCORE_SEQ.nextval,'C001','S000003',70);
--------------------------------------------------------
--  Insert into 提問 courseask
--------------------------------------------------------
INSERT INTO courseask (courseaskno,courseno,studentno,title,question,updatetime,status,isdelete) VALUES (COURSEASK_SEQ.nextval,'C001','S000001','ojdbc6.jar只能搭配oracle的資料庫嗎?','ojdbc6.jar只能搭配oracle的資料庫嗎?...etc',to_timestamp('2020-07-02 20:30:00','YYYY-MM-DD HH24:MI:SS'),1,0);
INSERT INTO courseask (courseaskno,courseno,studentno,title,question,updatetime,status,isdelete) VALUES (COURSEASK_SEQ.nextval,'C002','S000002','執行Java應用程式必須安裝Java執行時環境JRE嗎?','執行Java應用程式必須安裝Java執行時環境JRE嗎?...etc',to_timestamp('2020-09-07 17:30:00','YYYY-MM-DD HH24:MI:SS'),1,0);
INSERT INTO courseask (courseaskno,courseno,studentno,title,question,updatetime,status,isdelete) VALUES (COURSEASK_SEQ.nextval,'C003','S000003','JAVA類別名的首字母應該大寫，方法名應該以小寫字母開頭嗎?','JAVA類別名的首字母應該大寫，方法名應該以小寫字母開頭嗎?...etc',to_timestamp('2020-10-26 08:30:00','YYYY-MM-DD HH24:MI:SS'),1,0);
--------------------------------------------------------
--  Insert into 提問回覆 reply
--------------------------------------------------------
INSERT INTO reply (replyno,courseaskno,teacherno,studentno,replycontent,updatetime) VALUES (REPLY_SEQ.nextval,'1','T000001',null,'是的',to_timestamp('2020-07-02 20:33:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO reply (replyno,courseaskno,teacherno,studentno,replycontent,updatetime) VALUES (REPLY_SEQ.nextval,'2','T000001',null,'是的',to_timestamp('2020-09-07 17:33:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO reply (replyno,courseaskno,teacherno,studentno,replycontent,updatetime) VALUES (REPLY_SEQ.nextval,'3','T000002',null,'是的',to_timestamp('2020-10-26 09:33:00','YYYY-MM-DD HH24:MI:SS'));
--------------------------------------------------------
--  Insert into 課表 timetable
--------------------------------------------------------
INSERT INTO timetable (timetableno,courseno,classroomno,timetableperiod,timetabledate,teachinglog,isdelete) VALUES ('TT'||LPAD(to_char(TIMETABLE_SEQ.NEXTVAL), '6', '0'),'C001','1',0,TO_DATE('2020-07-01','YYYY-MM-DD'),'1. JDBC導論...etc',0);
INSERT INTO timetable (timetableno,courseno,classroomno,timetableperiod,timetabledate,teachinglog,isdelete) VALUES ('TT'||LPAD(to_char(TIMETABLE_SEQ.NEXTVAL), '6', '0'),'C002','1',1,TO_DATE('2020-07-01','YYYY-MM-DD'),'2. 資料庫連線...etc',0);
INSERT INTO timetable (timetableno,courseno,classroomno,timetableperiod,timetabledate,teachinglog,isdelete) VALUES ('TT'||LPAD(to_char(TIMETABLE_SEQ.NEXTVAL), '6', '0'),'C003','1',2,TO_DATE('2020-07-01','YYYY-MM-DD'),'3. JNDI VS JDBC ...etc',0);
--------------------------------------------------------
--  Insert into 教材 teachingfile
--------------------------------------------------------
INSERT INTO teachingfile (teachingfileno,timetableno,teachingfilename) VALUES (TEACHINGFILE_SEQ.nextval,'TT000001','JDBC講義.pdf');
INSERT INTO teachingfile (teachingfileno,timetableno,teachingfilename) VALUES (TEACHINGFILE_SEQ.nextval,'TT000002','JDBC範例.pdf');
INSERT INTO teachingfile (teachingfileno,timetableno,teachingfilename) VALUES (TEACHINGFILE_SEQ.nextval,'TT000003','JAVA講義.pdf');
--------------------------------------------------------
--  Insert into 課堂影片 video
--------------------------------------------------------
INSERT INTO video (videono,timetableno,videoname) VALUES (VIDEO_SEQ.nextval,'TT000001','2020-07-01 早上');
INSERT INTO video (videono,timetableno,videoname) VALUES (VIDEO_SEQ.nextval,'TT000002','2020-07-01 下午');
INSERT INTO video (videono,timetableno,videoname) VALUES (VIDEO_SEQ.nextval,'TT000003','2020-07-01 晚上');
--------------------------------------------------------
--  Insert into 影片觀看紀錄 videolog
--------------------------------------------------------
INSERT INTO videolog (videologno,videono,watchtime,status) VALUES (VIDEOLOG_SEQ.nextval,'1','120',1);
INSERT INTO videolog (videologno,videono,watchtime,status) VALUES (VIDEOLOG_SEQ.nextval,'1','280',1);
INSERT INTO videolog (videologno,videono,watchtime,status) VALUES (VIDEOLOG_SEQ.nextval,'1','140',1);
--------------------------------------------------------
--  Insert into 健康管理表 healthlog
--------------------------------------------------------
INSERT INTO healthlog (healthlogno, studentno, status, healthlogdate) VALUES (HEALTHLOG_SEQ.nextval, 'S000001', 1, TO_DATE('2020-09-25','YYYY-MM-DD'));
INSERT INTO healthlog (healthlogno, studentno, status, healthlogdate) VALUES (HEALTHLOG_SEQ.nextval, 'S000002', 1, TO_DATE('2020-09-25','YYYY-MM-DD'));
INSERT INTO healthlog (healthlogno, studentno, status, healthlogdate) VALUES (HEALTHLOG_SEQ.nextval, 'S000003', 1, TO_DATE('2020-09-25','YYYY-MM-DD'));
--------------------------------------------------------
--  Insert into 請假 leave
--------------------------------------------------------
INSERT INTO leave (leaveno, studentno, timetableno, type, description, status) VALUES (LEAVE_SEQ.nextval, 'S000001', 'TT000001', 1, '感冒', '1');
INSERT INTO leave (leaveno, studentno, timetableno, type, description, status) VALUES (LEAVE_SEQ.nextval, 'S000002', 'TT000001', 2, '家族旅遊', '1');
INSERT INTO leave (leaveno, studentno, timetableno, type, description, status) VALUES (LEAVE_SEQ.nextval, 'S000003', 'TT000001', 1, '感冒', '1');
--------------------------------------------------------
--  Insert into 出缺勤 attendance
--------------------------------------------------------
INSERT INTO attendance (attendanceno, studentno, timetableno, time, status, note) VALUES (ATTENDANCE_SEQ.nextval, 'S000001', 'TT000001', to_timestamp('2020-09-25 09:01:00','YYYY-MM-DD HH24:MI:SS'), 1, ' ' );
INSERT INTO attendance (attendanceno, studentno, timetableno, time, status, note) VALUES (ATTENDANCE_SEQ.nextval, 'S000002', 'TT000001', null, 2, '忘記打卡' );
INSERT INTO attendance (attendanceno, studentno, timetableno, time, status, note) VALUES (ATTENDANCE_SEQ.nextval, 'S000003', 'TT000001', null, 3, '看診' );
--------------------------------------------------------
--  commit
--------------------------------------------------------
commit;